[Business]
[Business.invokes]
target = "Capital"
[Business.recruits]
target = "Performer"
[Business.adopts]
target = "Doctrine"

[Business.Church]
[Business.Corporation]
[Business.Family]
[Business.Gang]
[Business.Government]

[Capital]
[Capital.Asset]
[Capital.Connection]
[Capital.Cultural]
[Capital.Monetary]
[Capital.Political]
[Capital.Social]

[Doctrine]
[Doctrine.informs]
target = "Performance"
[Doctrine.Breakdown]

[Doctrine.Design]

[Gesture]
[Gesture.hand]
target = "Participant"
[Gesture.head]
target = "Performer"
[Gesture.state]
target = "State"
[Gesture.Speech]

[Event]
[Event.generates]
target = "Capital"

[Event.Broadcast]
[Event.Inspiration]

[Instrument]
# Instruments generate rhythm. Axes, Guns, Microwave ovens, Pianos
[Instrument.embodies]
target = "Technology"

[Instrument.Driving]
[Instrument.Driving.Hammer]
[Instrument.Driving.Hammer.embodies]
target = "Technology.Metallurgy"
[Instrument.Forming]
[Instrument.Forming.Anvil]
[Instrument.Forming.Anvil.embodies]
target = "Technology.Metallurgy"
[Instrument.Musical]
[Instrument.Musical.Synthesiser]
[Instrument.Text]
[Instrument.Text.Code]

[Mythology]

[Mythology.Character]
[Mythology.Character.values]
target = "Capital.Social"
[Mythology.Class]
[Mythology.Class.values]
target = "Capital.Political"
[Mythology.Credit]
[Mythology.Credit.values]
target = "Capital.Monetary"
[Mythology.Family]
[Mythology.Family.values]
target = "Capital.Connection"
[Mythology.Friendship]
[Mythology.Friendship.values]
target = "Capital.Connection"
[Mythology.Nation]
[Mythology.Nation.values]
target = "Capital.Cultural"
[Mythology.Ownership]
[Mythology.Ownership.values]
target = "Capital.Asset"

[Participant]
[Participant.internalises]
target = "Mythology"
[Participant.witnesses]
target = "Event"

[Participant.Heidegger]
[Participant.Heidegger.experiences]
target = "Event.Inspiration"

[Performance]
# Performances span time

[Performance.creates]
target = "Event"

[Performance.Reading]
[Performance.Reading.performs]
target = "Instrument.Text"
[Performance.Recital]
[Performance.Recital.pronounces]
target = "Instrument.Text"
[Performance.Thinking]
[Performance.Writing]
[Performance.Writing.arranges]
target = "Instrument.Text"

[Performer]
[Performer.delivers]
target = "Performance"
[Performer.formulates]
target = "Doctrine"
[Performer.practices]
target = "Instrument"
[Performer.discovers]
target = "Technology"
[Performer.Heidegger]
[Performer.Heidegger.formulates]
target = "Doctrine.Breakdown"
[Performer.Heidegger.begins]
target = "Performance.Thinking"

[State]

[Technology]

[Technology.Audio]
[Technology.Metallurgy]
[Technology.Language]
[Technology.Language.CSS]
[Technology.Language.HTML]
[Technology.Language.PDF]
[Technology.Language.Python]
[Technology.Language.Python.Software]
[Technology.Language.Python.Software.Balladeer]
[Technology.Language.Python.Software.Docutils]
[Technology.Language.Python.Software.Proclets]
[Technology.Language.RestructuredText]
[Technology.Language.TOML]
[Technology.Network]
[Technology.Printing]
[Technology.Printing.reifies]
target = "Instrument.Text"
[Technology.Web]
[Technology.Web.distributes]
target = "Instrument.Text"
[Technology.OS.Linux]
[Technology.Video]

