[Business]
[Business.accesses]
target = "Capital"
[Business.develops]
target = "Technology"
[Business.schedules]
target = "Event"
[Business.promotes]
target = "Performer"

[Capital]


[Event]
[Event.delivers]
target = "Performance"
[Event.generates]
target = "Capital"
[Event.requires]
target = "Technology"

[Event.Broadcast]

[Instrument]
[Instrument.embodies]
target = "Technology"

[Instrument.Synth]
[Instrument.Voice]

[Mythology]

[Mythology.Class]
[Mythology.Culture]

[Participant]
[Participant.witnesses]
target = "Event"

[Performance]

[Performance.Jam]
[Performance.Recital]
[Performance.Theatre]

[Performer]
[Performer.creates]
target = "Performance"
[Performer.practices]
target = "Instrument"

[Technology]
[Technology.Audio]
[Technology.Computing]
[Technology.Network]
[Technology.Video]

