[Business]
[Business.accesses]
target = "Capital"
[Business.develops]
target = "Technology"
[Business.schedules]
target = "Event"
[Business.sponsors]
target = "Performer"
[Business.promotes]
target = "Doctrine"

[Business.Corporation]
[Business.Firm]
[Business.Government]

[Capital]
[Capital.Cultural]
[Capital.Monetary]
[Capital.Political]
[Capital.Social]

[Doctrine]
[Doctrine.informs]
target = "Performance"
[Doctrine.Breakdown]

[Gesture]
[Gesture.hand]
target = "Participant"
[Gesture.head]
target = "Performer"
[Gesture.state]
target = "State"
[Gesture.Speech]

[Event]
[Event.generates]
target = "Capital"

[Event.Broadcast]
[Event.Inspiration]

[Instrument]
# Instruments generate rhythm. Axes, Guns, Microwave ovens, Pianos

[Instrument.Synth]
[Instrument.Text]

[Mythology]

[Mythology.Character]
[Mythology.Character.values]
target = "Capital.Social"
[Mythology.Class]
[Mythology.Class.values]
target = "Capital.Political"
[Mythology.Credit]
[Mythology.Credit.values]
target = "Capital.Monetary"
[Mythology.Nation]
[Mythology.Nation.values]
target = "Capital.Cultural"

[Participant]
[Participant.internalises]
target = "Mythology"
[Participant.witnesses]
target = "Event"

[Participant.Heidegger]
[Participant.Heidegger.experiences]
target = "Event.Inspiration"

[Performance]
# Performances span time

[Performance.delivers]
target = "Event"

[Performance.Reading]
[Performance.Recital]
[Performance.Recital.performs]
target = "Instrument.Text"
[Performance.Thinking]
[Performance.Writing]
[Performance.Writing.arranges]
target = "Instrument.Text"

[Performer]
[Performer.creates]
target = "Performance"
[Performer.formulates]
target = "Doctrine"
[Performer.practices]
target = "Instrument"
[Performer.Heidegger]
[Performer.Heidegger.formulates]
target = "Doctrine.Breakdown"
[Performer.Heidegger.begins]
target = "Performance.Thinking"

[State]

[Technology]
[Technology.enables]
target = "Event"
[Technology.implements]
target = "Instrument"

[Technology.Audio]
[Technology.Computing]
[Technology.Network]
[Technology.Printing]
[Technology.Printing.copies]
target = "Instrument.Text"
[Technology.Video]

