[Business]
[Business.accesses]
target = "Capital"
[Business.develops]
target = "Technology"
[Business.formulates]
target = "Doctrine"
[Business.schedules]
target = "Event"
[Business.promotes]
target = "Performer"

[Capital]

[Change]

[Doctrine]
[Doctrine.codifies]
target = "Performance"

[Gesture]

[Event]
[Event.generates]
target = "Capital"
[Event.requires]
target = "Technology"

[Event.Broadcast]

[Instrument]
# Instruments generate rhythm. Axes, Guns, Microwave ovens, Pianos

[Instrument.embodies]
target = "Technology"

[Instrument.Synth]
[Instrument.Text]
[Instrument.Voice]

[Mythology]

[Mythology.Class]
[Mythology.Culture]

[Participant]
[Participant.witnesses]
target = "Event"
[Participant.undergoes]
target = "Change"

[Performance]
# Performances span time

[Performance.delivers]
target = "Event"

[Performance.Jam]
[Performance.Recital]
[Performance.Speech]
# Speech Act
[Performance.Theatre]

[Performer]
[Performer.creates]
target = "Performance"
[Performer.practices]
target = "Instrument"

[Technology]
[Technology.Audio]
[Technology.Computing]
[Technology.Network]
[Technology.Video]

