[Mythology]
[Mythology.Class]
[Mythology.Class.politics]
target = "Performance.Theatre"

[Mythology.Culture]
[Mythology.Culture.music]
target = "Performance.Broadcast"

[Performance]
[Performance.Vlog]
[Performance.Jam]
[Performance.Jam.stream]
target = "Technology.Network"
[Performance.Broadcast]
[Performance.Broadcast.stream]
target = "Technology.Network"
[Performance.Theatre]

[Technology]
[Technology.Network]
[Technology.Synth]
[Technology.Synth.perform]
target = "Performance.Jam"
