[Business]
[Business.invokes]
target = "Capital"
[Business.recruits]
target = "Performer"
[Business.adopts]
target = "Doctrine"

[Business.Church]
label = "Church"
[Business.Corporation]
label = "Corporation"
[Business.Family]
label = "Family"
[Business.Government]
label = "Government"

[Capital]
[Capital.Asset]
[Capital.Connection]
[Capital.Cultural]
[Capital.Monetary]
[Capital.Political]
[Capital.Social]

[Doctrine]
color = {"r" = 0, "g" = 0, "b" = 0}
[Doctrine.informs]
target = "Act"
color = {"r" = 0, "g" = 0, "b" = 0}

[Doctrine.Design]
label = "Design"
[Doctrine.Design.Game]
label = "Games"
[Doctrine.Design.Game.Audio]
label = "FX"
[Doctrine.Design.Game.Audio.Barks]
label = "barks"
[Doctrine.Design.Game.Mechanics]
label = "Mechanics"
[Doctrine.Design.Game.Mechanics.Crafting]
label = "crafting"
[Doctrine.Design.Game.Mechanics.DayNightCycle]
label = "day/night cycles"
[Doctrine.Philosophy]
[Doctrine.Philosophy.Breakdown]

[Instrument.Conceptual.Gesture]
color = {"r" = 0, "g" = 0, "b" = 0}
fill = {"r" = 0, "g" = 0, "b" = 0, "a" = 255}
stroke = {"r" = 0, "g" = 0, "b" = 0, "a" = 255}
label = "Gesture"
[Instrument.Conceptual.Gesture.hand]
target = "Participant"
[Instrument.Conceptual.Gesture.head]
target = "Performer"
[Instrument.Conceptual.Gesture.negotiates]
target = "State"
[Instrument.Conceptual.Gesture.Vocal]
label = "speech"

[Event]
[Event.generates]
target = "Capital"

[Event.Broadcast]
label = "Broadcast"
[Event.Story]
label = "Story"
[Event.Inspiration]
label = "Inspiration"

[Instrument]
# Instruments generate rhythm. Axes, Guns, Microwave ovens, Pianos
[Instrument.incorporates]
target = "Technology"

[Instrument.Conceptual]
label = "Concept"
[Instrument.Conceptual.PetriNet]
label = "Petri Nets"
[Instrument.Driving]
[Instrument.Driving.Hammer]
label = "hammer"
[Instrument.Driving.Hammer.embodies]
target = "Technology.Metallurgy"
[Instrument.Forming]
[Instrument.Forming.Anvil]
label = "anvil"
[Instrument.Forming.Anvil.embodies]
target = "Technology.Metallurgy"
[Instrument.Musical]
label = "Sound"
[Instrument.Musical.Synthesiser]
label = "Synths"
[Instrument.Text]
label = "Text"
[Instrument.Text.Code]
label = "Code"

[Mythology]

[Mythology.Character]
label = "Character"
[Mythology.Character.values]
target = "Capital.Social"
[Mythology.Class]
label = "Class"
[Mythology.Class.values]
target = "Capital.Political"
[Mythology.Credit]
label = "Credit"
[Mythology.Credit.values]
target = "Capital.Monetary"
[Mythology.Family]
label = "Ancestry"
[Mythology.Family.values]
target = "Capital.Connection"
[Mythology.Friendship]
label = "Friendship/Emnity"
[Mythology.Friendship.values]
target = "Capital.Connection"
[Mythology.Nation]
label = "Nationhood"
[Mythology.Nation.values]
target = "Capital.Cultural"
[Mythology.Ownership]
label = "Ownership"
[Mythology.Ownership.values]
target = "Capital.Asset"

[Participant]
[Participant.internalises]
target = "Mythology"
[Participant.witnesses]
target = "Event"

[Participant.Heidegger]
label = "Martin Heidegger"
[Participant.Heidegger.experiences]
target = "Event.Inspiration"

[Act]
# Acts span time

[Act.creates]
target = "Event"

[Act.Reading]
[Act.Reading.vivifies]
target = "Instrument.Text"
[Act.Recital]
label = "Recital"
[Act.Recital.pronounces]
target = "Instrument.Text"
[Act.Thinking]
label = "Thinking"
[Act.Writing]
label = "Writing"
[Act.Writing.arranges]
target = "Instrument.Text"

[Performer]
[Performer.performs]
target = "Act"
[Performer.formulates]
target = "Doctrine"
[Performer.practices]
target = "Instrument"
[Performer.discovers]
target = "Technology"
[Performer.Heidegger]
label = "Martin Heidegger"
[Performer.Heidegger.nexus]
target = "Participant.Heidegger"
label = "..."
[Performer.Heidegger.formulates]
target = "Doctrine.Philosophy.Breakdown"
[Performer.Heidegger.begins]
target = "Act.Thinking"

[State]
label = "state"

[Technology]

[Technology.Audio]
[Technology.Metallurgy]
label="Metallurgy"
[Technology.Language]
[Technology.Language.CSS]
label="CSS"
[Technology.Language.HTML]
label="HTML"
[Technology.Language.PDF]
label="PDF"
[Technology.Language.Python]
label="Python"
[Technology.Language.Python.Software]
[Technology.Language.Python.Software.comprises]
target = "Instrument.Text.Code"
[Technology.Language.Python.Software.Balladeer]
label="balladeer"
[Technology.Language.Python.Software.Docutils]
label="docutils"
[Technology.Language.Python.Software.Proclets]
label="proclets"
[Technology.Language.Python.Software.Proclets.implements]
target = "Instrument.Conceptual.PetriNet"
[Technology.Language.RestructuredText]
label="rST"
[Technology.Language.TOML]
label="TOML"
[Technology.Network]
label="Network"
[Technology.Printing]
label="Printing"
[Technology.Printing.reifies]
target = "Instrument.Text"
[Technology.Web]
[Technology.Web.distributes]
target = "Instrument.Text"
[Technology.OS]
label="OS"
[Technology.OS.Linux]
label="Linux"
[Technology.Video]

